language: java
jdk: oraclejdk11

script: mvn -e verify

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - arthurganeev@list.ru
    on_failure: always
    on_succes: change